### ISSUE TITLE
Zero Shot Image Classification Task Page

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#351]
This is the tracker for completion of task page for zero-shot-image-classification task. The page is here: https://huggingface.co/tasks/zero-shot-image-classification You can contribute parts of a task or the whole task! (There's no single assignee to a task, these are wikipedia-like pages)
You can refer to https://github.com/huggingface/hub-docs/issues/369 if you want to contribute! 🤗

List of items to contribute:

- [ ] Task description
- [ ] Subtasks (if there is any)
- [ ] Most used dataset for the task
- [ ] Most used model for the task
- [ ] Metrics that are used to evaluate the task
- [ ] Libraries used for the task
- [ ] Use cases
- [ ] Small snippet for inference that demonstrates the task

**Comment by silvererudite** [comment]
Hi @merveenoyan I would like to contribute here pls...would start with `Task description`, `Most used dataset for the task` and `Most used model for the task` for now

**Comment by silvererudite** [comment]
@merveenoyan after cloning my fork, I wanted to view the docs locally  before making any changes but not being able to `preview` I ran this command `doc-builder preview hub F:\hub-docs\docs\hub\ --not_python_module` from Windows cmd and get this error 
```
F:\>doc-builder preview hub \hub-docs\docs\hub\ --not_python_module
Initial build docs for hub \hub-docs\docs\hub\ C:\Users\Admin\AppData\Local\Temp\tmprc0m6nf0\hub\main\en
Building the MDX files: 100%|█████████████████████████████████████████████████████████| 74/74 [00:00<00:00, 296.00it/s]
Generating frontmatter: 100%|█████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 233.59it/s]
Installing node dependencies

Watching for changes in: F:\hub-docs

Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\doc_builder\commands\preview.py", line 132, in start_sveltekit_dev
    subprocess.run(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by 02shanks** [comment]
Hi @merveenoyan I would like to contribute to Task description and use cases

**Comment by YaegerKnight** [comment]
Hello @merveenoyan , I'd like to work on the `Most used dataset for the task` and `Metrics that are used to evaluate the task`

**Comment by merveenoyan** [comment]
@YaegerKnight metrics are added by @silvererudite but if you have any other metric feel free to add 🙂 the datasets work!

**Comment by YaegerKnight** [comment]
Sure @merveenoyan. I'll take a look at that. Thank you

**Comment by YaegerKnight** [comment]
@merveenoyan I see that datasets in the `TaskData` is empty in #380. May I ask why this was closed?

**Comment by merveenoyan** [comment]
@YaegerKnight feel free to contribute, one of the PRs were linked with `fixes` and it automatically closes the issue when PR is merged. I re-opened it.

**Comment by merveenoyan** [comment]
@chefhaider @YaegerKnight currently the following are missing, would you still be up to contribute?

List of items to contribute:

 Subtasks (if there is any)
 Most used dataset for the task
 Libraries used for the task
 Use cases
 Small snippet for inference that demonstrates the task
 Task Schema
 Model for Widget

**Comment by chefhaider** [comment]
@merveenoyan Absolutely! for now I'll be picking up Uses Cases and Small snippets.

**Comment by p4arth** [comment]
Hi @merveenoyan could you assign me "Small snippet for inference that demonstrates the task"?

**Comment by osanseviero** [comment]
Lots of cool contributions! :fire:  At the moment, the only missing piece is some datasets
